### ISSUE TITLE
App iOS 

### ISSUE THREAD

**Issue by michelmelo** [tomahock/suprimidos.pt#1]
Já tem alguém a fazer o aplicativo iOS?

**Comment by tomahock** [comment]
Sim! Na realidade já está feito, estamos a usar Flutter para criar as aplicações tanto para Android como para iOS.
O código está aqui: https://github.com/FogosPT/suprimidosmobile

Estamos só à espera da aprovação da AppStore que já submetemos a aplicação!

**Comment by michelmelo** [comment]
ok. ;)
